<Project Sdk="Aspire.AppHost.Sdk/13.4.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>4ff4e67f-7c50-4d8d-91fc-db79777ecd2b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CommunityToolkit.Aspire.Hosting.GlitchTip.ApiService/CommunityToolkit.Aspire.Hosting.GlitchTip.ApiService.csproj" />
    <ProjectReference Include="../CommunityToolkit.Aspire.Hosting.GlitchTip.Web/CommunityToolkit.Aspire.Hosting.GlitchTip.Web.csproj" />
    <ProjectReference Include="..\..\..\src\CommunityToolkit.Aspire.Hosting.GlitchTip\CommunityToolkit.Aspire.Hosting.GlitchTip.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Docker" />
  </ItemGroup>

</Project>
