//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class GlitchTipBuilderExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.GlitchTipResource> AddGlitchTip(this IDistributedApplicationBuilder builder, string name, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> adminEmail, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> adminPassword, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? secretKey = null, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? orgName = null, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? projectName = null, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? fromEmail = null, int? port = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.GlitchTipResource> WithDeployTimeProvisioning(this ApplicationModel.IResourceBuilder<ApplicationModel.GlitchTipResource> builder) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.GlitchTipResource> WithPostgres(this ApplicationModel.IResourceBuilder<ApplicationModel.GlitchTipResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.PostgresDatabaseResource> database) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.GlitchTipResource> WithRedis(this ApplicationModel.IResourceBuilder<ApplicationModel.GlitchTipResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.RedisResource> redis) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    [AspireExport(ExposeProperties = true)]
    public partial class GlitchTipResource : ContainerResource, IResourceWithConnectionString, IResource, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public GlitchTipResource(string name, ParameterResource secretKey, ParameterResource adminEmail, ParameterResource adminPassword, ParameterResource orgName, ParameterResource projectName) : base(default!, default) { }

        public ParameterResource AdminEmail { get { throw null; } }

        public ParameterResource AdminPassword { get { throw null; } }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public string? DsnKey { get { throw null; } }

        public ParameterResource OrgName { get { throw null; } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }

        public string? ProjectId { get { throw null; } }

        public ParameterResource ProjectName { get { throw null; } }

        public ParameterResource SecretKey { get { throw null; } }
    }
}