//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CommunityToolkit.Aspire.GlitchTip
{
    public sealed partial class GlitchTipSettings
    {
        public bool DisableHealthChecks { get { throw null; } set { } }

        public string? Dsn { get { throw null; } set { } }
    }
}

namespace Microsoft.Extensions.Hosting
{
    public static partial class AspireGlitchTipExtensions
    {
        public static void AddGlitchTipClient(this AspNetCore.Builder.WebApplicationBuilder builder, string connectionName, System.Action<CommunityToolkit.Aspire.GlitchTip.GlitchTipSettings>? configureSettings = null) { }
    }
}