<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AdditionalPackageTags>hosting glitchtip sentry</AdditionalPackageTags>
    <Description>GlitchTip support for Aspire.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Redis" />
  </ItemGroup>

</Project>
