<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AdditionalPackageTags>glitchtip sentry client</AdditionalPackageTags>
    <Description>GlitchTip client integration for Aspire. Wires up the Sentry SDK with the DSN injected by the Aspire AppHost.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <PackageReference Include="AspNetCore.HealthChecks.Uris" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Sentry.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(SharedDir)\HealthChecksExtensions.cs" Link="Utils\HealthChecksExtensions.cs" />
  </ItemGroup>

</Project>
